"""
Extract gods/patrons data from Death Timer PDF into gods.json
Also renames extracted images to match god names.
"""
import json, os, re, shutil

DATA_DIR = os.path.join(os.path.dirname(__file__), 'static', 'data')
IMG_DIR  = os.path.join(os.path.dirname(__file__), 'static', 'images', 'gods')

# Manually parsed from Death Timer Issue 1, pages 36-43
gods = [
    # === LAWFUL DEITIES (pages 36-37) ===
    {
        "id": "avandra",
        "name": "Avandra",
        "title": "The Change Bringer",
        "alignment": "Lawful",
        "type": "Deity",
        "domain": "Trickery",
        "description": "Goddess of change, freedom, good fortune, and luck.",
        "aka": ["Tyche"],
        "pantheons": ["Dawn War", "Exandrian", "Greek", "Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 36,
        "image": ""
    },
    {
        "id": "berronar_truesilver",
        "name": "Berronar Truesilver",
        "title": "The Revered Mother",
        "alignment": "Lawful",
        "type": "Deity",
        "domain": "Peace",
        "description": "Dwarven goddess of hearth and home.",
        "aka": [],
        "pantheons": ["Dwarven", "Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 36,
        "image": ""
    },
    {
        "id": "chauntea",
        "name": "Chauntea",
        "title": "The Grain Mother",
        "alignment": "Lawful",
        "type": "Deity",
        "domain": "Life",
        "description": "Goddess of agriculture.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 36,
        "image": ""
    },
    {
        "id": "corellon_larethian",
        "name": "Corellon Larethian",
        "title": "The Arch Heart",
        "alignment": "Lawful",
        "type": "Deity",
        "domain": "Light, Magic",
        "description": "Elven god of art and magic.",
        "aka": [],
        "pantheons": ["Dawn War", "Elven", "Exandrian", "Faerûnian", "Greyhawkian"],
        "servants": [],
        "followers": ["Pornicus"],
        "source": "Death Timer Issue 1",
        "page": 36,
        "image": ""
    },
    {
        "id": "haela_brightaxe",
        "name": "Haela Brightaxe",
        "title": "The Luckmaiden",
        "alignment": "Lawful",
        "type": "Deity",
        "domain": "Luck",
        "description": "Dwarven goddess of war-luck. She is known to take great risks in battle, fight without hesitation, and support dwarves who also do so.",
        "aka": [],
        "pantheons": ["Dwarven", "Faerûnian"],
        "servants": [],
        "followers": ["Nadja Brüenôrdōttír"],
        "source": "Death Timer Issue 1",
        "page": 36,
        "image": "haela_brightaxe.png"
    },
    {
        "id": "kord",
        "name": "Kord",
        "title": "The Storm Lord",
        "alignment": "Lawful",
        "type": "Deity",
        "domain": "Tempest",
        "description": "God of battle, competition, athletics, sport, and storms.",
        "aka": [],
        "pantheons": ["Dawn War", "Exandrian", "Greyhawkian"],
        "servants": ["Thor"],
        "followers": ["Moon Blackwell", "Tony Sparx (aka Sparky)"],
        "source": "Death Timer Issue 1",
        "page": 36,
        "image": ""
    },
    {
        "id": "mielikki",
        "name": "Mielikki",
        "title": "The Forest Queen",
        "alignment": "Lawful",
        "type": "Deity",
        "domain": "Nature",
        "description": "Goddess of forests and nature.",
        "aka": [],
        "pantheons": ["Faerûnian", "Finnish"],
        "servants": ["Gwaeron Windstrom"],
        "followers": ["Bob Oakheart", "Idril Taargo"],
        "source": "Death Timer Issue 1",
        "page": 37,
        "image": ""
    },
    {
        "id": "selune",
        "name": "Selûne",
        "title": "The Moonmaiden",
        "alignment": "Lawful",
        "type": "Deity",
        "domain": "Moon",
        "description": "Goddess of the moon. Her teachings of compassion and guidance are popular with those striving under moon light. Aka The Triple Goddess (including Eilistraee and Hecate).",
        "aka": ["The Triple Goddess"],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": ["Milton Moonbringer"],
        "source": "Death Timer Issue 1",
        "page": 37,
        "image": "selune.png"
    },
    {
        "id": "torm",
        "name": "Torm",
        "title": "The Loyal Fury",
        "alignment": "Lawful",
        "type": "Deity",
        "domain": "War",
        "description": "God of courage and self-sacrifice. Torm sees Tyr as a father figure, and Ilmater as a brother in arms.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 37,
        "image": "torm.png"
    },
    {
        "id": "tymora",
        "name": "Tymora",
        "title": "Lady Luck",
        "alignment": "Lawful",
        "type": "Deity",
        "domain": "Luck",
        "description": "Goddess of good fortune.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 37,
        "image": ""
    },
    {
        "id": "tyr",
        "name": "Tyr",
        "title": "The Evenhanded",
        "alignment": "Lawful",
        "type": "Deity",
        "domain": "Order",
        "description": "God of justice, courage and strategy. An ancient god known on many worlds for bringing justice to the oppressed.",
        "aka": [],
        "pantheons": ["Faerûnian", "Norse"],
        "servants": ["St. Cuthbert", "St. Terragnis"],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 37,
        "image": ""
    },

    # === NEUTRAL DEITIES (pages 38-39) ===
    {
        "id": "eilistraee",
        "name": "Eilistraee",
        "title": "Dark Maiden",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "Moon",
        "description": "Drow goddess of beauty, dance, song, and moonlight. Aka The Triple Goddess.",
        "aka": ["The Triple Goddess"],
        "pantheons": ["Drow", "Faerûnian"],
        "servants": [],
        "followers": ["Tarkina Riverbend"],
        "source": "Death Timer Issue 1",
        "page": 38,
        "image": ""
    },
    {
        "id": "eldath",
        "name": "Eldath",
        "title": "The Quiet One",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "Peace",
        "description": "Goddess of peace.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 38,
        "image": ""
    },
    {
        "id": "erathis",
        "name": "Erathis",
        "title": "The Law Bearer",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "Order",
        "description": "Goddess of civilization, peace, and invention.",
        "aka": ["Athena"],
        "pantheons": ["Dawn War", "Greek", "Exandrian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 38,
        "image": ""
    },
    {
        "id": "freya",
        "name": "Freya",
        "title": "Lady of Fire",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "Life",
        "description": "Goddess of fertility and love.",
        "aka": [],
        "pantheons": ["Norse", "Shadowdark"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 38,
        "image": ""
    },
    {
        "id": "gond",
        "name": "Gond",
        "title": "Wonderbringer",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "Forge",
        "description": "God of craft.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 38,
        "image": ""
    },
    {
        "id": "helm",
        "name": "Helm",
        "title": "The Watcher",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "Light",
        "description": "God of protection and watchfulness.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 38,
        "image": ""
    },
    {
        "id": "jergel",
        "name": "Jergel",
        "title": "The Pitiless One",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "Death",
        "description": "Scribe of the dead.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 38,
        "image": ""
    },
    {
        "id": "mask",
        "name": "Mask",
        "title": "The Lord of All Shadows",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "Trickery",
        "description": "Goddess of thieves.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": ["Notinel Not' Shadow"],
        "source": "Death Timer Issue 1",
        "page": 39,
        "image": ""
    },
    {
        "id": "mystra",
        "name": "Mystra",
        "title": "The Lady of Mysteries",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "Magic",
        "description": "Goddess of magic.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 39,
        "image": ""
    },
    {
        "id": "oghma",
        "name": "Oghma",
        "title": "The Binder",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "Knowledge",
        "description": "God of knowledge, speech and writing.",
        "aka": ["Ord"],
        "pantheons": ["Celtic", "Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 39,
        "image": ""
    },
    {
        "id": "raven_queen",
        "name": "Raven Queen",
        "title": "Nickname",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "Grave",
        "description": "Goddess of death, fate, and winter.",
        "aka": ["Hel"],
        "pantheons": ["Faerûnian", "Norse"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 39,
        "image": ""
    },
    {
        "id": "silvanus",
        "name": "Silvanus",
        "title": "The Oakfather",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "Nature",
        "description": "God of wild nature and forests.",
        "aka": ["Gede"],
        "pantheons": ["Celtic", "Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 39,
        "image": ""
    },
    {
        "id": "tempus",
        "name": "Tempus",
        "title": "The Foehammer",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "War",
        "description": "God of war.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 39,
        "image": ""
    },
    {
        "id": "waukeen",
        "name": "Waukeen",
        "title": "The Coinmaiden",
        "alignment": "Neutral",
        "type": "Deity",
        "domain": "Trickery",
        "description": "Goddess of trade and merchants.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": ["Gnomebody", "Bedivere Darkale", "Gary Glittergold"],
        "source": "Death Timer Issue 1",
        "page": 39,
        "image": ""
    },

    # === CHAOTIC DEITIES (pages 40-41) ===
    {
        "id": "beshaba",
        "name": "Beshaba",
        "title": "Lady Doom",
        "alignment": "Chaotic",
        "type": "Deity",
        "domain": "Luck",
        "description": "Goddess of bad luck.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 40,
        "image": "beshaba.png"
    },
    {
        "id": "gruumsh",
        "name": "Gruumsh",
        "title": "The Ruiner",
        "alignment": "Chaotic",
        "type": "Deity",
        "domain": "War",
        "description": "Orc god of slaughter, warfare, and destruction.",
        "aka": ["Rammlat the Pillager"],
        "pantheons": ["Dawn War", "Exandrian", "Faerûnian", "Greyhawkian", "Orc", "Shadowdark"],
        "servants": [],
        "followers": ["Tor"],
        "source": "Death Timer Issue 1",
        "page": 40,
        "image": ""
    },
    {
        "id": "hecate",
        "name": "Hecate",
        "title": "Dread Goddess of Night",
        "alignment": "Chaotic",
        "type": "Deity",
        "domain": "Moon",
        "description": "Goddess of magic and the moon. Aka The Triple Goddess (with Eilistraee and Selûne).",
        "aka": ["The Triple Goddess"],
        "pantheons": ["Greek"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 40,
        "image": "hecate.png"
    },
    {
        "id": "iuz",
        "name": "Iuz",
        "title": "The Old, Wicked One",
        "alignment": "Chaotic",
        "type": "Deity",
        "domain": "Death",
        "description": "God of pain and oppression. Half cambion son of Iggwilv and Grazzt.",
        "aka": [],
        "pantheons": ["Greyhawkian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 40,
        "image": ""
    },
    {
        "id": "lolth",
        "name": "Lolth",
        "title": "The Spider Queen",
        "alignment": "Chaotic",
        "type": "Deity",
        "domain": "Trickery",
        "description": "Drow goddess of spiders and deceit.",
        "aka": ["Memnon"],
        "pantheons": ["Dawn War", "Drow", "Exandrian", "Faerûnian", "Greyhawkian"],
        "servants": ["Belphegor", "Loki"],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 41,
        "image": "lolth.png"
    },
    {
        "id": "malar",
        "name": "Malar",
        "title": "The Beastlord",
        "alignment": "Chaotic",
        "type": "Deity",
        "domain": "Nature",
        "description": "God of the hunt. He hunts on the Prime Material Plane.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 41,
        "image": ""
    },
    {
        "id": "myrkul",
        "name": "Myrkul",
        "title": "The Lord of Bones",
        "alignment": "Chaotic",
        "type": "Deity",
        "domain": "Death",
        "description": "God of death.",
        "aka": [],
        "pantheons": ["Faerûnian"],
        "servants": ["Iuz", "Lovitar", "Talona", "Zehir"],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 41,
        "image": "myrkul.png"
    },
    {
        "id": "surtur",
        "name": "Surtur",
        "title": "Lord of the Fire Giants",
        "alignment": "Chaotic",
        "type": "Deity",
        "domain": "Forge",
        "description": "God of fire giants.",
        "aka": [],
        "pantheons": ["Faerûnian", "Giant", "Greyhawkian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 41,
        "image": "surtur.png"
    },
    {
        "id": "tiamat",
        "name": "Tiamat",
        "title": "The Scaled Tyrant",
        "alignment": "Chaotic",
        "type": "Deity",
        "domain": "Order",
        "description": "Dragon goddess of wealth, greed, vengeance, and evil.",
        "aka": [],
        "pantheons": ["Exandrian", "Faerûnian"],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 41,
        "image": "tiamat.png"
    },

    # === PATRONS (pages 42-43) ===
    {
        "id": "asmodeus",
        "name": "Asmodeus",
        "title": "The Lord of the Nine Hells",
        "alignment": "Chaotic",
        "type": "Patron",
        "domain": "Knowledge",
        "description": "Archdevil god of indulgence, domination and tyranny. One of the most powerful beings in the multiverse, Asmodeus, is not content to just rule the Hells, but seeks to rule over all of existence, as well. He loves tempting mortals through the \"seven deadly sins\" of mankind.",
        "aka": ["Kytheros"],
        "pantheons": ["All"],
        "servants": ["Titivillus"],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 42,
        "image": "asmodeus.png"
    },
    {
        "id": "belphegor",
        "name": "Belphegor",
        "title": "The Dark Prodigy",
        "alignment": "Chaotic",
        "type": "Patron",
        "domain": "",
        "description": "Belphegor is the daughter of Asmodeus, and an unpredictable archdevil succubi with her own agenda, known for her subversiveness. The \"Princess of the Nine Hells,\" is one of the most hated by other devil rulers, including her part-time lover, Mammon. She also enjoys toying with mortals.",
        "aka": ["Almazzat", "Glasya"],
        "pantheons": [],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 42,
        "image": "belphegor.png"
    },
    {
        "id": "iggwilv",
        "name": "Iggwilv",
        "title": "The Witch Queen",
        "alignment": "Chaotic",
        "type": "Patron",
        "domain": "",
        "description": "Iggwilv was once a famous wizard called Tasha. The child of Baba Yaga, Iggwilv was the mother of god Iuz, with her demon lover Grazz't. She seeks hidden secrets and lost lore.",
        "aka": ["Shune the Vile"],
        "pantheons": [],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 43,
        "image": "iggwilv.png"
    },
    {
        "id": "jubilex",
        "name": "Jubilex",
        "title": "Lord of Ooze",
        "alignment": "Chaotic",
        "type": "Patron",
        "domain": "",
        "description": "The disgusting Lord of Ooze leaks between the cracks in memory and the darkness between the stars. Jubilex seeks \"the Dissolution\" of all physical form.",
        "aka": ["Mugdulblub"],
        "pantheons": [],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 43,
        "image": ""
    },
    {
        "id": "titania",
        "name": "Titania",
        "title": "Faerie Queen",
        "alignment": "Chaotic",
        "type": "Patron",
        "domain": "",
        "description": "The fickle archfey Faerie Queen of the Fey who views all of existence as a whimsical dream with hidden meaning and poignant drama. Titania seeks mischief, beauty, and artistry.",
        "aka": [],
        "pantheons": [],
        "servants": [],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 43,
        "image": ""
    },
    {
        "id": "vecna",
        "name": "Vecna",
        "title": "The Whispered One",
        "alignment": "Chaotic",
        "type": "Patron",
        "domain": "Magic",
        "description": "Lich god of evil secrets and necromancy. He often stalks nightmares. He seeks secrets of time, and offers power to those who can get them.",
        "aka": ["Shune the Vile"],
        "pantheons": ["Faerûnian", "Greyhawkian"],
        "servants": ["Iggwilv", "the Willowman"],
        "followers": [],
        "source": "Death Timer Issue 1",
        "page": 43,
        "image": "vecna.png"
    },
]

# Image mapping based on page position analysis:
# Page 36 img0 (right, y82-239): near Haela Brightaxe / Kord area
# Page 37 img0 (left, y15-247): near Torm (top-left)
# Page 37 img1 (right, y221-425): near Selûne/Mielikki area
# Page 38 img0 (left, y87-357): large neutral deities art (decorative)
# Page 39 img0 (right, full column): decorative art for neutral deities
# Page 40 img0 (right, y87-333): near Beshaba
# Page 40 img1 (left, y170-395): near Hecate
# Page 41 img0 (left, y-5-212): near Myrkul (top-left)
# Page 41 img1 (left, y354-469): near Surtur/Malar
# Page 41 img2 (right, y125-360): near Lolth / Tiamat area
# Page 42 img0 (left, y154-321): Asmodeus area
# Page 42 img1 (right, y87-336): Belphegor area
# Page 43 img0 (left, y-60-274): Iggwilv area
# Page 43 img1 (right, y165-388): Vecna area

image_renames = {
    "page36_img0_450x450.png": "haela_brightaxe.png",
    "page37_img0_500x718.png": "torm.png",
    "page37_img1_640x800.png": "selune.png",
    "page38_img0_1178x1888.png": "neutral_deities_art.png",
    "page39_img0_428x1694.png": "neutral_deities_art2.png",
    "page40_img0_246x380.png": "beshaba.png",
    "page40_img1_250x345.png": "hecate.png",
    "page41_img0_750x1000.png": "myrkul.png",
    "page41_img1_900x639.png": "surtur.png",
    "page41_img2_157x228.png": "tiamat.png",
    "page42_img0_640x640.png": "asmodeus.png",
    "page42_img1_497x750.png": "belphegor.png",
    "page43_img0_724x934.png": "iggwilv.png",
    "page43_img1_620x930.png": "vecna.png",
}

def main():
    os.makedirs(IMG_DIR, exist_ok=True)
    os.makedirs(DATA_DIR, exist_ok=True)

    # Rename images
    for old_name, new_name in image_renames.items():
        src = os.path.join(IMG_DIR, old_name)
        dst = os.path.join(IMG_DIR, new_name)
        if os.path.exists(src):
            shutil.copy2(src, dst)
            print(f"  Copied {old_name} -> {new_name}")

    # Write JSON
    out_path = os.path.join(DATA_DIR, 'gods.json')
    with open(out_path, 'w', encoding='utf-8') as f:
        json.dump(gods, f, indent=2, ensure_ascii=False)
    print(f"\nWrote {len(gods)} gods to {out_path}")

if __name__ == '__main__':
    main()
